### ISSUE TITLE
panic: unknown time zone Local"

### ISSUE THREAD

**Issue by lynzhai** [bydmm/giligili#5]
go run main.go 运行时出现panic: unknown time zone Local"，是我哪里配置有问题吗

**Comment by lynzhai** [comment]
connString := "root:12344321@/giligili?charset=utf8&parseTime=True&loc=Local"
	//connString := "root:12344321@/giligili?charset=utf8&parseTime=True&loc=Local"
	dbConnectString := os.Getenv("MYSQL_DSN")
	fmt.Println("dbConnectString:", dbConnectString)
	model.Database(connString)

如果直接用connString 在model.Database(connString) ，就不会报错
如果从环境中获取，就会报错，我打印了环境变量中的os.Getenv("MYSQL_DSN") 和connString，是一摸一样的，但是用环境变量的就是不行

**Comment by bydmm** [comment]
你的说法很奇怪，似乎在说os.Getenv得到的string和直接的string，两个string不是===似的

**Comment by 9547** [comment]
> go run main.go 运行时出现 panic: unknown time zone Local"，是我哪里配置有问题吗

错误信息是指 `unknown time zone Local"`（末尾多了个 `"`)

这个问题可能是由于环境变量设置的时候有问题，比如以下面这种方式设置：

```bash
MYSQL_DSN="root:12344321@/giligili?charset=utf8&parseTime=True&loc=Local\"" 
```

末尾多了一个 `"`.
